import type { CharacterStructure } from '@hanzi/shared';

/**
 * Один символ из встроенного словаря этимологий.
 *
 * Это подмножество (≈150 самых частотных иероглифов HSK 1–2),
 * собранное вручную из открытых источников: cjk-decomp, Make Me a Hanzi
 * (компоненты), Unihan (радикалы и число черт).
 *
 * Данных не претендуют на академическую полноту — это понятные
 * пользователю объяснения для карточки «Происхождение».
 */
export interface DictionaryEntry {
  /** Иероглиф. */
  character: string;
  /** Количество черт. */
  strokeCount: number;
  /** Радикал. */
  radical: {
    character: string;
    number: number;
    name: string;
    meaning: string;
  };
  /** Структурный тип. */
  structure: CharacterStructure;
  /** Составляющие. */
  components: Array<{
    character: string;
    pinyin: string | null;
    meaning: string;
    role: 'semantic' | 'phonetic' | 'both';
  }>;
  /** Краткое происхождение/история. */
  etymology: string;
  /** Краткая мнемоника. */
  mnemonic: string;
}

/**
 * Встроенный словарь этимологий. Ключ — иероглиф.
 *
 * Источники компонентов/радикалов:
 *  - cjk-decomp (https://github.com/cjk-decomp/cjk-decomp) — публичный,
 *    лицензия MIT.
 *  - Unihan Database (https://www.unicode.org/charts/unihan.html) — UCD,
 *    радикал 1–214 и количество черт.
 *  - Make Me a Hanzi (https://github.com/skishore/makemeahanzi) —
 *    лицензия Arphic Public License.
 */
export const ETYMOLOGY_DICTIONARY: Readonly<Record<string, DictionaryEntry>> = {
  // ===== HSK 1 =====
  一: {
    character: '一',
    strokeCount: 1,
    radical: { character: '一', number: 1, name: '一', meaning: 'один' },
    structure: 'simple',
    components: [
      { character: '一', pinyin: 'yī', meaning: 'одна горизонтальная черта', role: 'both' },
    ],
    etymology:
      'Самая простая пиктограмма — одна горизонтальная черта, символ единственного целого.',
    mnemonic: 'Просто «одна» палочка.',
  },
  七: {
    character: '七',
    strokeCount: 2,
    radical: { character: '七', number: 5, name: '七', meaning: 'семь' },
    structure: 'simple',
    components: [
      { character: '七', pinyin: 'qī', meaning: 'семь (исторически — отрезать)', role: 'both' },
    ],
    etymology:
      'Изначально изображало крест с отрезанным куском — символ отделения «седьмой» части.',
    mnemonic: 'Короткая палочка поверх длинной — отсюда «семь».',
  },
  三: {
    character: '三',
    strokeCount: 3,
    radical: { character: '一', number: 1, name: '一', meaning: 'один' },
    structure: 'top-bottom',
    components: [
      { character: '一', pinyin: 'yī', meaning: 'один', role: 'both' },
      { character: '一', pinyin: 'yī', meaning: 'один', role: 'both' },
      { character: '一', pinyin: 'yī', meaning: 'один', role: 'both' },
    ],
    etymology: 'Три горизонтальные черты — буквально «один + один + один».',
    mnemonic: 'Три палочки = три.',
  },
  上: {
    character: '上',
    strokeCount: 3,
    radical: { character: '一', number: 1, name: '一', meaning: 'один' },
    structure: 'top-bottom',
    components: [
      { character: '一', pinyin: null, meaning: 'граница (крыша/линия)', role: 'semantic' },
      { character: '丨', pinyin: null, meaning: 'вертикаль (поднимающаяся черта)', role: 'semantic' },
    ],
    etymology: 'Черта над вертикалью — «вверху», «сверху».',
    mnemonic: 'Палочка «выше» горизонтальной линии = «наверху».',
  },
  下: {
    character: '下',
    strokeCount: 3,
    radical: { character: '一', number: 1, name: '一', meaning: 'один' },
    structure: 'top-bottom',
    components: [
      { character: '一', pinyin: null, meaning: 'граница (линия)', role: 'semantic' },
      { character: '丨', pinyin: null, meaning: 'вертикаль (черта вниз)', role: 'semantic' },
    ],
    etymology: 'Черта под горизонталью — «внизу».',
    mnemonic: 'Палочка «ниже» линии = «внизу».',
  },
  不: {
    character: '不',
    strokeCount: 4,
    radical: { character: '一', number: 1, name: '一', meaning: 'один' },
    structure: 'top-bottom',
    components: [
      { character: '一', pinyin: null, meaning: 'горизонталь', role: 'semantic' },
      { character: '丿', pinyin: null, meaning: 'отрицательный наклон', role: 'semantic' },
      { character: '一', pinyin: null, meaning: 'горизонталь', role: 'semantic' },
    ],
    etymology: 'Исторически изображало птицу, летящую вниз — символ отрицания.',
    mnemonic: 'Черта вниз-наискосок — «не».',
  },
  们: {
    character: '们',
    strokeCount: 5,
    radical: { character: '亻', number: 9, name: '人', meaning: 'человек' },
    structure: 'left-right',
    components: [
      { character: '亻', pinyin: null, meaning: 'человек (упрощённый радикал)', role: 'semantic' },
      { character: '门', pinyin: 'mén', meaning: 'ворота / категория (фонетик)', role: 'phonetic' },
    ],
    etymology:
      'Современный суффикс множественного числа людей: «люди из одной категории».',
    mnemonic: 'Человек + категория (ворота) = «они».',
  },
  认: {
    character: '认',
    strokeCount: 9,
    radical: { character: '讠', number: 149, name: '言', meaning: 'речь' },
    structure: 'left-right',
    components: [
      { character: '讠', pinyin: null, meaning: 'речь (упрощённый радикал 言)', role: 'semantic' },
      { character: '人', pinyin: 'rén', meaning: 'человек (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Речь + человек = «узнавать», «признавать».',
    mnemonic: '«Слово» + «человек» = «узнать».',
  },
  八: {
    character: '八',
    strokeCount: 2,
    radical: { character: '八', number: 12, name: '八', meaning: 'восемь / разделять' },
    structure: 'simple',
    components: [
      { character: '八', pinyin: 'bā', meaning: 'разделение на две части', role: 'both' },
    ],
    etymology: 'Изначально изображало разделение предмета на две половины.',
    mnemonic: 'Раскрытые в стороны черты = «восемь», «разделить».',
  },
  公: {
    character: '公',
    strokeCount: 4,
    radical: { character: '八', number: 12, name: '八', meaning: 'разделять' },
    structure: 'top-bottom',
    components: [
      { character: '八', pinyin: null, meaning: 'разделение', role: 'semantic' },
      { character: '厶', pinyin: null, meaning: 'частное', role: 'semantic' },
    ],
    etymology: '«Частное, отделенное для общего» — отсюда «общественный, справедливый».',
    mnemonic: 'Отделить от себя — «общее».',
  },
  六: {
    character: '六',
    strokeCount: 4,
    radical: { character: '八', number: 12, name: '八', meaning: 'разделять' },
    structure: 'overlap',
    components: [
      { character: '亠', pinyin: null, meaning: 'крышка', role: 'semantic' },
      { character: '八', pinyin: null, meaning: 'разделение', role: 'semantic' },
    ],
    etymology: 'Исторически — знак «六», производный от знака «八».',
    mnemonic: 'Крышка + «восемь» = «шесть».',
  },
  几: {
    character: '几',
    strokeCount: 2,
    radical: { character: '几', number: 16, name: '几', meaning: 'стол / несколько' },
    structure: 'simple',
    components: [
      { character: '几', pinyin: 'jǐ', meaning: 'маленький столик', role: 'both' },
    ],
    etymology: 'Пиктограмма маленького столика на ножках.',
    mnemonic: 'Маленький столик = «сколько, несколько».',
  },
  儿: {
    character: '儿',
    strokeCount: 2,
    radical: { character: '儿', number: 10, name: '儿', meaning: 'ребёнок' },
    structure: 'simple',
    components: [
      { character: '儿', pinyin: 'ér', meaning: 'ребёнок', role: 'both' },
    ],
    etymology: 'Изображение ребёнка (схематично — голова и тело).',
    mnemonic: 'Изгиб тела = «дитя».',
  },
  匕: {
    character: '匕',
    strokeCount: 2,
    radical: { character: '匕', number: 18, name: '匕', meaning: 'ложка' },
    structure: 'simple',
    components: [
      { character: '匕', pinyin: 'bǐ', meaning: 'ложка/кинжал', role: 'both' },
    ],
    etymology: 'Профиль ложки или короткого клинка.',
    mnemonic: 'Заострённый «клюв» = «ложка».',
  },
  北: {
    character: '北',
    strokeCount: 5,
    radical: { character: '匕', number: 18, name: '匕', meaning: 'ложка' },
    structure: 'overlap',
    components: [
      { character: '匕', pinyin: null, meaning: 'ложка', role: 'semantic' },
      { character: '匕', pinyin: null, meaning: 'ложка (зеркальная)', role: 'semantic' },
    ],
    etymology: 'Две «спинки к спине» — древний способ указать «север» (поворот спиной).',
    mnemonic: 'Спина к спине = «север».',
  },
  九: {
    character: '九',
    strokeCount: 2,
    radical: { character: '乙', number: 5, name: '乙', meaning: 'второй' },
    structure: 'simple',
    components: [
      { character: '九', pinyin: 'jiǔ', meaning: 'девять', role: 'both' },
    ],
    etymology: 'Исторически — окончание/хвост (乙), стало числом «девять».',
    mnemonic: 'Крючок + изгиб = «девять».',
  },
  习: {
    character: '习',
    strokeCount: 3,
    radical: { character: '乙', number: 5, name: '乙', meaning: 'второй' },
    structure: 'top-bottom',
    components: [
      { character: '习', pinyin: 'xí', meaning: 'дважды/повторять', role: 'both' },
    ],
    etymology: 'Изначально «крылья птицы, машущие дважды» = «тренироваться, практиковать».',
    mnemonic: 'Два крыла = «тренироваться».',
  },
  了: {
    character: '了',
    strokeCount: 2,
    radical: { character: '亅', number: 4, name: '丿', meaning: 'косая черта' },
    structure: 'simple',
    components: [
      { character: '亅', pinyin: null, meaning: 'завершение', role: 'semantic' },
    ],
    etymology: 'Исторически изображало ребёнка — маркер завершённости действия.',
    mnemonic: '«Законченный» ребёнок (крест) = 了.',
  },
  刀: {
    character: '刀',
    strokeCount: 2,
    radical: { character: '刀', number: 18, name: '刀', meaning: 'нож' },
    structure: 'simple',
    components: [
      { character: '刀', pinyin: 'dāo', meaning: 'нож', role: 'both' },
    ],
    etymology: 'Профиль ножа с рукояткой.',
    mnemonic: 'Лезвие + ручка = «нож».',
  },
  力: {
    character: '力',
    strokeCount: 2,
    radical: { character: '力', number: 19, name: '力', meaning: 'сила' },
    structure: 'simple',
    components: [
      { character: '力', pinyin: 'lì', meaning: 'сила', role: 'both' },
    ],
    etymology: 'Схематичное изображение согнутой в напряжении руки.',
    mnemonic: 'Согнутая «рука» = «сила».',
  },
  办: {
    character: '办',
    strokeCount: 5,
    radical: { character: '力', number: 19, name: '力', meaning: 'сила' },
    structure: 'left-right',
    components: [
      { character: '亅', pinyin: null, meaning: 'сокращение от 才', role: 'semantic' },
      { character: '力', pinyin: null, meaning: 'сила/действие', role: 'semantic' },
    ],
    etymology: 'Способность + сила = «справляться, вести дела».',
    mnemonic: '«Способность» + «сила» = «делать».',
  },
  又: {
    character: '又',
    strokeCount: 2,
    radical: { character: '又', number: 29, name: '又', meaning: 'снова / правая рука' },
    structure: 'simple',
    components: [
      { character: '又', pinyin: 'yòu', meaning: 'правая рука (исторически)', role: 'both' },
    ],
    etymology: 'Профиль правой руки — «снова», «ещё».',
    mnemonic: 'Изогнутая «рука» = «опять».',
  },
  口: {
    character: '口',
    strokeCount: 3,
    radical: { character: '口', number: 30, name: '口', meaning: 'рот' },
    structure: 'simple',
    components: [
      { character: '口', pinyin: 'kǒu', meaning: 'рот', role: 'both' },
    ],
    etymology: 'Простой квадрат — открытый рот.',
    mnemonic: 'Квадрат = «рот», «отверстие».',
  },
  吃: {
    character: '吃',
    strokeCount: 6,
    radical: { character: '口', number: 30, name: '口', meaning: 'рот' },
    structure: 'left-right',
    components: [
      { character: '口', pinyin: null, meaning: 'рот', role: 'semantic' },
      { character: '乞', pinyin: 'qǐ', meaning: 'просить (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Рот просит — отсюда «есть, кушать».',
    mnemonic: 'Рот + просящий = «есть».',
  },
  喝: {
    character: '喝',
    strokeCount: 12,
    radical: { character: '口', number: 30, name: '口', meaning: 'рот' },
    structure: 'left-right',
    components: [
      { character: '口', pinyin: null, meaning: 'рот', role: 'semantic' },
      { character: '曷', pinyin: 'hé', meaning: 'что? (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Ртом кричать что?» — «пить, кричать».',
    mnemonic: 'Рот + «что» = «пить/кричать».',
  },
  吗: {
    character: '吗',
    strokeCount: 6,
    radical: { character: '口', number: 30, name: '口', meaning: 'рот' },
    structure: 'left-right',
    components: [
      { character: '口', pinyin: null, meaning: 'рот', role: 'semantic' },
      { character: '马', pinyin: 'mǎ', meaning: 'лошадь (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Рот + «лошадь» (фонетик) = вопросительная частица.',
    mnemonic: 'Ртом вопрошать = «а? не так ли?»',
  },
  国: {
    character: '国',
    strokeCount: 8,
    radical: { character: '囗', number: 31, name: '囗', meaning: 'ограда' },
    structure: 'surrounding',
    components: [
      { character: '囗', pinyin: null, meaning: 'ограда, граница', role: 'semantic' },
      { character: '玉', pinyin: 'yù', meaning: 'нефрит/драгоценность', role: 'phonetic' },
    ],
    etymology: 'Драгоценность внутри ограды = «государство».',
    mnemonic: '«Нефрит» внутри «ограды» = «государство».',
  },
  因: {
    character: '因',
    strokeCount: 6,
    radical: { character: '囗', number: 31, name: '囗', meaning: 'ограда' },
    structure: 'surrounding',
    components: [
      { character: '囗', pinyin: null, meaning: 'ограда', role: 'semantic' },
      { character: '大', pinyin: 'dà', meaning: 'большой (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Большой» внутри ограды = «причина, опора».',
    mnemonic: 'Большое внутри = «причина».',
  },
  园: {
    character: '园',
    strokeCount: 7,
    radical: { character: '囗', number: 31, name: '囗', meaning: 'ограда' },
    structure: 'surrounding',
    components: [
      { character: '囗', pinyin: null, meaning: 'ограда', role: 'semantic' },
      { character: '元', pinyin: 'yuán', meaning: 'первоначальный (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Ограда вокруг «первоначального» = «сад, парк».',
    mnemonic: 'Огороженный участок = «сад».',
  },
  士: {
    character: '士',
    strokeCount: 3,
    radical: { character: '士', number: 33, name: '士', meaning: 'учёный' },
    structure: 'top-bottom',
    components: [
      { character: '士', pinyin: 'shì', meaning: 'учёный муж/воин', role: 'both' },
    ],
    etymology: 'Черты, отмечающие человека с достоинством — «учёный, воин».',
    mnemonic: '«Человек с двумя чертами» = «учёный».',
  },
  己: {
    character: '己',
    strokeCount: 3,
    radical: { character: '己', number: 49, name: '己', meaning: 'сам' },
    structure: 'simple',
    components: [
      { character: '己', pinyin: 'jǐ', meaning: 'сам', role: 'both' },
    ],
    etymology: 'Скрученный шнур — символ собственного, индивидуального.',
    mnemonic: 'Закрученный = «свой».',
  },
  已: {
    character: '已',
    strokeCount: 3,
    radical: { character: '已', number: 49, name: '已', meaning: 'уже' },
    structure: 'simple',
    components: [
      { character: '已', pinyin: 'yǐ', meaning: 'уже', role: 'both' },
    ],
    etymology: 'Исторически — завершённое действие (закрученный шнур).',
    mnemonic: 'Свернулся в узел = «уже».',
  },
  市: {
    character: '市',
    strokeCount: 5,
    radical: { character: '巾', number: 50, name: '巾', meaning: 'полотенце' },
    structure: 'top-bottom',
    components: [
      { character: '亠', pinyin: null, meaning: 'крышка/флаг', role: 'semantic' },
      { character: '巾', pinyin: 'jīn', meaning: 'полотенце/ткань', role: 'semantic' },
    ],
    etymology: 'Ткань под флагом = «рынок, город».',
    mnemonic: 'Ткань под вывеской = «рынок».',
  },
  师: {
    character: '师',
    strokeCount: 6,
    radical: { character: '巾', number: 50, name: '巾', meaning: 'полотенце' },
    structure: 'overlap',
    components: [
      { character: '帅', pinyin: 'shuài', meaning: 'командир (исторически)', role: 'semantic' },
      { character: '巾', pinyin: 'jīn', meaning: 'полотенце (массы)', role: 'semantic' },
    ],
    etymology: 'Командир + толпа = «учитель, мастер».',
    mnemonic: 'Командир над людьми = «учитель».',
  },
  希: {
    character: '希',
    strokeCount: 7,
    radical: { character: '巾', number: 50, name: '巾', meaning: 'полотенце' },
    structure: 'top-bottom',
    components: [
      { character: '乂', pinyin: null, meaning: 'управлять', role: 'semantic' },
      { character: '巾', pinyin: null, meaning: 'ткань (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Ткань, рассечённая надвое — «редкий, желанный».',
    mnemonic: 'Редкая ткань = «надеяться».',
  },
  干: {
    character: '干',
    strokeCount: 3,
    radical: { character: '干', number: 51, name: '干', meaning: 'сухой' },
    structure: 'simple',
    components: [
      { character: '干', pinyin: 'gān', meaning: 'сухое дерево/щит', role: 'both' },
    ],
    etymology: 'Схематичное изображение древка щита или сухого ствола.',
    mnemonic: 'Сухая палка-основа = «делать».',
  },
  平: {
    character: '平',
    strokeCount: 5,
    radical: { character: '干', number: 51, name: '干', meaning: 'сухой' },
    structure: 'top-bottom',
    components: [
      { character: '干', pinyin: null, meaning: 'основа', role: 'semantic' },
      { character: '一', pinyin: null, meaning: 'горизонт', role: 'semantic' },
    ],
    etymology: 'Горизонт, лежащий на основе = «ровный, мирный».',
    mnemonic: 'Горизонт на «основе» = «ровно».',
  },
  床: {
    character: '床',
    strokeCount: 7,
    radical: { character: '广', number: 53, name: '广', meaning: 'навес' },
    structure: 'top-bottom',
    components: [
      { character: '广', pinyin: null, meaning: 'навес/здание', role: 'semantic' },
      { character: '木', pinyin: 'mù', meaning: 'дерево (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Дерево под навесом = «кровать».',
    mnemonic: 'Дерево под крышей = «кровать».',
  },
  店: {
    character: '店',
    strokeCount: 8,
    radical: { character: '广', number: 53, name: '广', meaning: 'навес' },
    structure: 'top-bottom',
    components: [
      { character: '广', pinyin: null, meaning: 'навес', role: 'semantic' },
      { character: '占', pinyin: 'zhàn', meaning: 'занимать (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Занимать» под навесом = «лавка, магазин».',
    mnemonic: 'Под навесом продают = «магазин».',
  },
  建: {
    character: '建',
    strokeCount: 9,
    radical: { character: '廴', number: 54, name: '廴', meaning: 'длинный шаг' },
    structure: 'left-right',
    components: [
      { character: '廴', pinyin: null, meaning: 'длинная дорога', role: 'semantic' },
      { character: '聿', pinyin: null, meaning: 'кисть/действие', role: 'semantic' },
    ],
    etymology: '«Кистью по длинной дороге» = «строить».',
    mnemonic: 'Длинный путь + кисть = «строить».',
  },
  广: {
    character: '广',
    strokeCount: 3,
    radical: { character: '广', number: 53, name: '广', meaning: 'навес' },
    structure: 'simple',
    components: [
      { character: '广', pinyin: 'guǎng', meaning: 'навес/здание', role: 'both' },
    ],
    etymology: 'Схематичный навес/дом с открытой стороной.',
    mnemonic: '«Дом с крышей» = «обширный».',
  },
  心: {
    character: '心',
    strokeCount: 4,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'simple',
    components: [
      { character: '心', pinyin: 'xīn', meaning: 'сердце', role: 'both' },
    ],
    etymology: 'Изображение сердца (с «отростками» — сосудами).',
    mnemonic: '«Сердце» с артериями = «душа».',
  },
  必: {
    character: '必',
    strokeCount: 5,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'top-bottom',
    components: [
      { character: '八', pinyin: null, meaning: 'разделение', role: 'semantic' },
      { character: '心', pinyin: null, meaning: 'сердце', role: 'semantic' },
    ],
    etymology: '«Разделение сердца» = «непременно».',
    mnemonic: 'Сердце на распашку = «обязательно».',
  },
  思: {
    character: '思',
    strokeCount: 9,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'top-bottom',
    components: [
      { character: '田', pinyin: 'tián', meaning: 'поле', role: 'semantic' },
      { character: '心', pinyin: null, meaning: 'сердце', role: 'semantic' },
    ],
    etymology: '«Сердце на поле» — мысли вспахивают разум.',
    mnemonic: 'Поле + сердце = «думать».',
  },
  急: {
    character: '急',
    strokeCount: 7,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'top-bottom',
    components: [
      { character: '刍', pinyin: null, meaning: 'спешка/корм', role: 'semantic' },
      { character: '心', pinyin: null, meaning: 'сердце', role: 'semantic' },
    ],
    etymology: 'Сердце в спешке = «торопиться».',
    mnemonic: 'Сердце колотится = «срочно».',
  },
  怎: {
    character: '怎',
    strokeCount: 9,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'top-bottom',
    components: [
      { character: '乍', pinyin: 'zhà', meaning: 'вдруг (фонетик)', role: 'phonetic' },
      { character: '心', pinyin: null, meaning: 'сердце', role: 'semantic' },
    ],
    etymology: 'Сердце в растерянности = «как? почему?»',
    mnemonic: '«Как?» = вопрос сердцу.',
  },
  怕: {
    character: '怕',
    strokeCount: 8,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'left-right',
    components: [
      { character: '白', pinyin: 'bái', meaning: 'белый (фонетик)', role: 'phonetic' },
      { character: '心', pinyin: null, meaning: 'сердце', role: 'semantic' },
    ],
    etymology: '«Белое сердце» (побледневшее) = «бояться».',
    mnemonic: 'Побледневшее сердце = «страх».',
  },
  怪: {
    character: '怪',
    strokeCount: 8,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'left-right',
    components: [
      { character: '圣', pinyin: null, meaning: 'святой (искаж.)', role: 'semantic' },
      { character: '心', pinyin: null, meaning: 'сердце', role: 'semantic' },
    ],
    etymology: 'Странность в сердце = «удивляться, странный».',
    mnemonic: '«Сердце» на «святом» = «странно».',
  },
  您: {
    character: '您',
    strokeCount: 11,
    radical: { character: '心', number: 61, name: '心', meaning: 'сердце' },
    structure: 'top-bottom',
    components: [
      { character: '您', pinyin: 'nín', meaning: 'Вы (уважительно)', role: 'both' },
    ],
    etymology: '«Ты» + «сердце» (уважение) = вежливое «Вы».',
    mnemonic: '«Ты» с «сердцем» = «Вы» (уважительно).',
  },
  手: {
    character: '手',
    strokeCount: 4,
    radical: { character: '手', number: 64, name: '手', meaning: 'рука' },
    structure: 'simple',
    components: [
      { character: '手', pinyin: 'shǒu', meaning: 'рука', role: 'both' },
    ],
    etymology: 'Изображение кисти руки с растопыренными пальцами.',
    mnemonic: 'Растопыренные пальцы = «рука».',
  },
  打: {
    character: '打',
    strokeCount: 5,
    radical: { character: '扌', number: 64, name: '手', meaning: 'рука' },
    structure: 'left-right',
    components: [
      { character: '扌', pinyin: null, meaning: 'рука (упрощ.)', role: 'semantic' },
      { character: '丁', pinyin: 'dīng', meaning: 'гвоздь/муж (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Рукой по гвоздю» = «бить, ударять».',
    mnemonic: '«Рука» + «гвоздь» = «ударить».',
  },
  找: {
    character: '找',
    strokeCount: 7,
    radical: { character: '扌', number: 64, name: '手', meaning: 'рука' },
    structure: 'left-right',
    components: [
      { character: '扌', pinyin: null, meaning: 'рука', role: 'semantic' },
      { character: '戈', pinyin: 'gē', meaning: 'копьё (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Рукой с копьём искать цель = «искать».',
    mnemonic: '«Рука» ищет = «найти».',
  },
  拿: {
    character: '拿',
    strokeCount: 8,
    radical: { character: '扌', number: 64, name: '手', meaning: 'рука' },
    structure: 'left-right',
    components: [
      { character: '扌', pinyin: null, meaning: 'рука', role: 'semantic' },
      { character: '合', pinyin: 'hé', meaning: 'соединять (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Рукой «соединять» предметы = «брать».',
    mnemonic: '«Рука» + «соединить» = «взять».',
  },
  接: {
    character: '接',
    strokeCount: 12,
    radical: { character: '扌', number: 64, name: '手', meaning: 'рука' },
    structure: 'left-right',
    components: [
      { character: '扌', pinyin: null, meaning: 'рука', role: 'semantic' },
      { character: '妾', pinyin: 'qiè', meaning: 'наложница (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Рукой соединять = «получать, соединять».',
    mnemonic: '«Рука» + «соединять» = «принять».',
  },
  放: {
    character: '放',
    strokeCount: 8,
    radical: { character: '攵', number: 67, name: '攵', meaning: 'действие' },
    structure: 'left-right',
    components: [
      { character: '方', pinyin: 'fāng', meaning: 'квадрат/сторона (фонетик)', role: 'phonetic' },
      { character: '攵', pinyin: null, meaning: 'действие', role: 'semantic' },
    ],
    etymology: '«Действие в сторону» = «отпускать, ставить».',
    mnemonic: '«Действие» + «сторона» = «отпустить».',
  },
  故: {
    character: '故',
    strokeCount: 8,
    radical: { character: '攵', number: 67, name: '攵', meaning: 'действие' },
    structure: 'left-right',
    components: [
      { character: '古', pinyin: 'gǔ', meaning: 'старый (фонетик)', role: 'phonetic' },
      { character: '攵', pinyin: null, meaning: 'действие', role: 'semantic' },
    ],
    etymology: '«Действие из прошлого» = «причина, прошлое».',
    mnemonic: '«Старое» + «действие» = «причина».',
  },
  文: {
    character: '文',
    strokeCount: 4,
    radical: { character: '文', number: 67, name: '文', meaning: 'культура' },
    structure: 'simple',
    components: [
      { character: '文', pinyin: 'wén', meaning: 'узор/письмена', role: 'both' },
    ],
    etymology: 'Татуировка/узор на теле — символ культуры и письма.',
    mnemonic: 'Древний «узор» = «культура».',
  },
  方: {
    character: '方',
    strokeCount: 4,
    radical: { character: '方', number: 70, name: '方', meaning: 'квадрат / сторона' },
    structure: 'simple',
    components: [
      { character: '方', pinyin: 'fāng', meaning: 'квадрат, направление', role: 'both' },
    ],
    etymology: 'Сторона прямоугольника, изначально — геометрический знак.',
    mnemonic: 'Квадрат-стрелка = «сторона».',
  },
  旁: {
    character: '旁',
    strokeCount: 10,
    radical: { character: '方', number: 70, name: '方', meaning: 'квадрат' },
    structure: 'left-right',
    components: [
      { character: '立', pinyin: 'lì', meaning: 'стоять', role: 'semantic' },
      { character: '方', pinyin: null, meaning: 'сторона', role: 'semantic' },
    ],
    etymology: 'Стоящее «сбоку» = «рядом, около».',
    mnemonic: '«Стоять» + «сторона» = «рядом».',
  },
  旅: {
    character: '旅',
    strokeCount: 10,
    radical: { character: '方', number: 70, name: '方', meaning: 'квадрат' },
    structure: 'left-right',
    components: [
      { character: '亻', pinyin: null, meaning: 'человек (искаж.)', role: 'semantic' },
      { character: '方', pinyin: null, meaning: 'войско/сторона', role: 'semantic' },
    ],
    etymology: 'Люди, идущие строем = «путешествие, войско».',
    mnemonic: '«Люди» + «строй» = «путешествие».',
  },
  族: {
    character: '族',
    strokeCount: 11,
    radical: { character: '方', number: 70, name: '方', meaning: 'квадрат' },
    structure: 'left-right',
    components: [
      { character: '方', pinyin: null, meaning: 'флаг/клан', role: 'semantic' },
      { character: '矢', pinyin: null, meaning: 'стрела', role: 'semantic' },
    ],
    etymology: 'Клан под флагом с оружием = «род, нация».',
    mnemonic: '«Флаг» + «стрела» = «клан».',
  },
  无: {
    character: '无',
    strokeCount: 4,
    radical: { character: '无', number: 12, name: '无', meaning: 'отсутствие' },
    structure: 'overlap',
    components: [
      { character: '元', pinyin: 'yuán', meaning: 'первоначальный (искаж.)', role: 'semantic' },
      { character: '一', pinyin: null, meaning: 'нет', role: 'semantic' },
    ],
    etymology: 'Изначально «не-первоначальный» = «отсутствие».',
    mnemonic: '«Не»-«первоначальный» = «без».',
  },
  日: {
    character: '日',
    strokeCount: 4,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'simple',
    components: [
      { character: '日', pinyin: 'rì', meaning: 'солнце', role: 'both' },
    ],
    etymology: 'Солнце с горизонтом (или точкой внутри).',
    mnemonic: 'Квадрат с точкой = «солнце».',
  },
  旦: {
    character: '旦',
    strokeCount: 4,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'top-bottom',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '一', pinyin: null, meaning: 'земля', role: 'semantic' },
    ],
    etymology: 'Солнце, встающее над землёй = «заря, утро».',
    mnemonic: 'Солнце над линией = «заря».',
  },
  明: {
    character: '明',
    strokeCount: 8,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'left-right',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '月', pinyin: null, meaning: 'луна', role: 'semantic' },
    ],
    etymology: 'Солнце + Луна = «яркий, свет».',
    mnemonic: '«Солнце» + «Луна» = «свет».',
  },
  星: {
    character: '星',
    strokeCount: 9,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'top-bottom',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '生', pinyin: 'shēng', meaning: 'рождаться (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Свет, «рождающийся» в небе = «звезда».',
    mnemonic: '«Солнце» + «рождение» = «звезда».',
  },
  显: {
    character: '显',
    strokeCount: 9,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'left-right',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '业', pinyin: 'yè', meaning: 'дело (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Солнце» на «деле» = «явный, видимый».',
    mnemonic: '«Солнце» освещает = «явно».',
  },
  春: {
    character: '春',
    strokeCount: 9,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'top-bottom',
    components: [
      { character: '艹', pinyin: null, meaning: 'трава', role: 'semantic' },
      { character: '春', pinyin: 'chūn', meaning: 'весна', role: 'both' },
    ],
    etymology: '«Трава на солнце» = «весна».',
    mnemonic: 'Трава + солнце = «весна».',
  },
  昨: {
    character: '昨',
    strokeCount: 9,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'left-right',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '乍', pinyin: 'zhà', meaning: 'вдруг (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Солнце, что уже было» = «вчера».',
    mnemonic: '«Солнце» + «вдруг» = «вчера».',
  },
  时: {
    character: '时',
    strokeCount: 7,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'left-right',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '寺', pinyin: 'sì', meaning: 'храм (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Солнце над храмом = «время, час».',
    mnemonic: '«Солнце» + «храм» = «время».',
  },
  晚: {
    character: '晚',
    strokeCount: 11,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'left-right',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '免', pinyin: 'miǎn', meaning: 'освободить (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Солнце, что «ушло»» = «вечер».',
    mnemonic: 'Уходящее солнце = «вечер».',
  },
  月: {
    character: '月',
    strokeCount: 4,
    radical: { character: '月', number: 74, name: '月', meaning: 'луна / мясо' },
    structure: 'simple',
    components: [
      { character: '月', pinyin: 'yuè', meaning: 'луна', role: 'both' },
    ],
    etymology: 'Серп луны, позже — знак плоти (в составе).',
    mnemonic: 'Серп = «луна».',
  },
  期: {
    character: '期',
    strokeCount: 12,
    radical: { character: '月', number: 74, name: '月', meaning: 'луна' },
    structure: 'left-right',
    components: [
      { character: '其', pinyin: 'qí', meaning: 'его (фонетик)', role: 'phonetic' },
      { character: '月', pinyin: null, meaning: 'луна (месяц)', role: 'semantic' },
    ],
    etymology: '«Его месяц» = «срок, период».',
    mnemonic: '«Месяц» + «его» = «срок».',
  },
  木: {
    character: '木',
    strokeCount: 4,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'simple',
    components: [
      { character: '木', pinyin: 'mù', meaning: 'дерево', role: 'both' },
    ],
    etymology: 'Схематичное дерево с ветвями и корнями.',
    mnemonic: 'Ствол + ветви + корни = «дерево».',
  },
  本: {
    character: '本',
    strokeCount: 5,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'top-bottom',
    components: [
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
      { character: '一', pinyin: null, meaning: 'корень', role: 'semantic' },
    ],
    etymology: '«Корень дерева» = «основа, корень».',
    mnemonic: 'Дерево с подчёркнутым корнем = «основа».',
  },
  末: {
    character: '末',
    strokeCount: 5,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'top-bottom',
    components: [
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
      { character: '一', pinyin: null, meaning: 'верхушка', role: 'semantic' },
    ],
    etymology: '«Верхушка дерева» = «конец».',
    mnemonic: 'Дерево с подчёркнутой верхушкой = «конец».',
  },
  果: {
    character: '果',
    strokeCount: 8,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'top-bottom',
    components: [
      { character: '田', pinyin: 'tián', meaning: 'поле', role: 'semantic' },
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
    ],
    etymology: '«Поле» на «дереве» = «плод».',
    mnemonic: 'На дереве вырос «плод».',
  },
  林: {
    character: '林',
    strokeCount: 8,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'left-right',
    components: [
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
    ],
    etymology: 'Два дерева рядом = «лес, роща».',
    mnemonic: 'Два дерева = «лес».',
  },
  桌: {
    character: '桌',
    strokeCount: 16,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'left-right',
    components: [
      { character: '卓', pinyin: 'zhuó', meaning: 'высокий (фонетик)', role: 'phonetic' },
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
    ],
    etymology: '«Высокое» дерево = «стол».',
    mnemonic: '«Высокое» + «дерево» = «стол».',
  },
  杯: {
    character: '杯',
    strokeCount: 8,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'left-right',
    components: [
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
      { character: '不', pinyin: 'bù', meaning: 'нет (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Дерево, из которого «не» пить = «чашка».',
    mnemonic: 'Деревянная чашка.',
  },
  校: {
    character: '校',
    strokeCount: 10,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'left-right',
    components: [
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
      { character: '交', pinyin: 'jiāo', meaning: 'пересекать (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Деревянная перекладина = «школа, проверять».',
    mnemonic: '«Пересечение» на «дереве» = «школа».',
  },
  条: {
    character: '条',
    strokeCount: 11,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'top-bottom',
    components: [
      { character: '夂', pinyin: null, meaning: 'медленный шаг', role: 'semantic' },
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
    ],
    etymology: 'Длинная ветвь дерева = «полоса, статья».',
    mnemonic: 'Ветка дерева = «полоса».',
  },
  欠: {
    character: '欠',
    strokeCount: 4,
    radical: { character: '欠', number: 76, name: '欠', meaning: 'не хватать' },
    structure: 'simple',
    components: [
      { character: '欠', pinyin: 'qiàn', meaning: 'зевать/не хватать', role: 'both' },
    ],
    etymology: 'Изображение зевающего человека (открытый рот + язык).',
    mnemonic: 'Зевающий рот = «не хватает».',
  },
  歌: {
    character: '歌',
    strokeCount: 14,
    radical: { character: '欠', number: 76, name: '欠', meaning: 'не хватать' },
    structure: 'left-right',
    components: [
      { character: '哥', pinyin: 'gē', meaning: 'старший брат (фонетик)', role: 'phonetic' },
      { character: '欠', pinyin: null, meaning: 'открытый рот (пение)', role: 'semantic' },
    ],
    etymology: '«Брат» с открытым ртом = «песня».',
    mnemonic: '«Брат» поёт с открытым ртом = «песня».',
  },
  止: {
    character: '止',
    strokeCount: 4,
    radical: { character: '止', number: 77, name: '止', meaning: 'стоп' },
    structure: 'simple',
    components: [
      { character: '止', pinyin: 'zhǐ', meaning: 'стопа', role: 'both' },
    ],
    etymology: 'Схематичный отпечаток стопы — «остановиться».',
    mnemonic: 'Стопа = «остановиться».',
  },
  正: {
    character: '正',
    strokeCount: 5,
    radical: { character: '止', number: 77, name: '止', meaning: 'стоп' },
    structure: 'top-bottom',
    components: [
      { character: '止', pinyin: null, meaning: 'стопа', role: 'semantic' },
      { character: '一', pinyin: null, meaning: 'ровный', role: 'semantic' },
    ],
    etymology: 'Стопа, не отклоняющаяся от прямой = «правильно».',
    mnemonic: '«Прямая» стопа = «правильно».',
  },
  此: {
    character: '此',
    strokeCount: 6,
    radical: { character: '止', number: 77, name: '止', meaning: 'стоп' },
    structure: 'left-right',
    components: [
      { character: '止', pinyin: null, meaning: 'стопа', role: 'semantic' },
      { character: '匕', pinyin: null, meaning: 'человек (искаж.)', role: 'semantic' },
    ],
    etymology: 'Стопа «здесь» = «этот».',
    mnemonic: '«Стопа» + «человек» = «этот».',
  },
  母: {
    character: '母',
    strokeCount: 5,
    radical: { character: '母', number: 88, name: '母', meaning: 'мать' },
    structure: 'simple',
    components: [
      { character: '母', pinyin: 'mǔ', meaning: 'мать', role: 'both' },
    ],
    etymology: 'Изображение матери с ребёнком на руках.',
    mnemonic: 'Женщина с ребёнком = «мать».',
  },
  每: {
    character: '每',
    strokeCount: 7,
    radical: { character: '母', number: 88, name: '母', meaning: 'мать' },
    structure: 'top-bottom',
    components: [
      { character: '毋', pinyin: null, meaning: 'не делать', role: 'semantic' },
      { character: '母', pinyin: null, meaning: 'мать', role: 'semantic' },
    ],
    etymology: '«Мать, что не делает» = «каждая».',
    mnemonic: '«Каждая» — даже мать.',
  },
  比: {
    character: '比',
    strokeCount: 4,
    radical: { character: '比', number: 81, name: '比', meaning: 'сравнивать' },
    structure: 'left-right',
    components: [
      { character: '比', pinyin: 'bǐ', meaning: 'сравнение', role: 'both' },
    ],
    etymology: 'Два человека рядом — сравнение.',
    mnemonic: 'Двое рядом = «сравнить».',
  },
  毛: {
    character: '毛',
    strokeCount: 4,
    radical: { character: '毛', number: 82, name: '毛', meaning: 'шерсть' },
    structure: 'simple',
    components: [
      { character: '毛', pinyin: 'máo', meaning: 'шерсть/пух', role: 'both' },
    ],
    etymology: 'Изображение пучка шерсти или перьев.',
    mnemonic: '«Пучок» = «шерсть».',
  },
  水: {
    character: '水',
    strokeCount: 4,
    radical: { character: '水', number: 85, name: '水', meaning: 'вода' },
    structure: 'simple',
    components: [
      { character: '水', pinyin: 'shuǐ', meaning: 'вода', role: 'both' },
    ],
    etymology: 'Течение воды с каплями по бокам.',
    mnemonic: 'Поток с каплями = «вода».',
  },
  永: {
    character: '永',
    strokeCount: 5,
    radical: { character: '水', number: 85, name: '水', meaning: 'вода' },
    structure: 'simple',
    components: [
      { character: '永', pinyin: 'yǒng', meaning: 'вечный', role: 'both' },
    ],
    etymology: 'Изначально — водоворот; стало символом «вечности».',
    mnemonic: '«Водоворот» = «вечный».',
  },
  汉: {
    character: '汉',
    strokeCount: 5,
    radical: { character: '氵', number: 85, name: '水', meaning: 'вода' },
    structure: 'left-right',
    components: [
      { character: '氵', pinyin: null, meaning: 'вода (упрощ.)', role: 'semantic' },
      { character: '又', pinyin: 'yòu', meaning: 'снова (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Воды реки Хань (漢) — отсюда этноним «хань».',
    mnemonic: '«Вода» + «снова» = «Хань».',
  },
  没: {
    character: '没',
    strokeCount: 7,
    radical: { character: '氵', number: 85, name: '水', meaning: 'вода' },
    structure: 'left-right',
    components: [
      { character: '氵', pinyin: null, meaning: 'вода', role: 'semantic' },
      { character: '殳', pinyin: 'shū', meaning: 'бить (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Вода, бьющая предмет = «тонуть, нет».',
    mnemonic: '«Вода» топит = «не/утонуть».',
  },
  法: {
    character: '法',
    strokeCount: 8,
    radical: { character: '氵', number: 85, name: '水', meaning: 'вода' },
    structure: 'left-right',
    components: [
      { character: '氵', pinyin: null, meaning: 'вода', role: 'semantic' },
      { character: '去', pinyin: 'qù', meaning: 'уходить (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Вода, что уходит» = «метод, закон» (вода-уравнитель).',
    mnemonic: '«Вода» + «уходить» = «закон».',
  },
  活: {
    character: '活',
    strokeCount: 9,
    radical: { character: '氵', number: 85, name: '水', meaning: 'вода' },
    structure: 'left-right',
    components: [
      { character: '氵', pinyin: null, meaning: 'вода', role: 'semantic' },
      { character: '舌', pinyin: 'shé', meaning: 'язык (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Вода» + «язык» = «живой» (вода жизни + речь).',
    mnemonic: '«Вода» + «язык» = «живой».',
  },
  火: {
    character: '火',
    strokeCount: 4,
    radical: { character: '火', number: 86, name: '火', meaning: 'огонь' },
    structure: 'simple',
    components: [
      { character: '火', pinyin: 'huǒ', meaning: 'огонь', role: 'both' },
    ],
    etymology: 'Изображение пламени с языками.',
    mnemonic: 'Языки пламени = «огонь».',
  },
  炎: {
    character: '炎',
    strokeCount: 8,
    radical: { character: '火', number: 86, name: '火', meaning: 'огонь' },
    structure: 'top-bottom',
    components: [
      { character: '火', pinyin: null, meaning: 'огонь', role: 'semantic' },
      { character: '火', pinyin: null, meaning: 'огонь', role: 'semantic' },
    ],
    etymology: 'Огонь над огнём = «жар, пламя».',
    mnemonic: 'Два огня = «жар».',
  },
  照: {
    character: '照',
    strokeCount: 13,
    radical: { character: '灬', number: 86, name: '火', meaning: 'огонь' },
    structure: 'left-right',
    components: [
      { character: '昭', pinyin: 'zhāo', meaning: 'ясный (фонетик)', role: 'phonetic' },
      { character: '灬', pinyin: null, meaning: 'огонь (упрощ.)', role: 'semantic' },
    ],
    etymology: '«Ясный» + «огонь» = «освещать, снимать».',
    mnemonic: 'Свет от «огня» = «освещать».',
  },
  烧: {
    character: '烧',
    strokeCount: 8,
    radical: { character: '灬', number: 86, name: '火', meaning: 'огонь' },
    structure: 'left-right',
    components: [
      { character: '尧', pinyin: 'yáo', meaning: 'император (фонетик)', role: 'phonetic' },
      { character: '灬', pinyin: null, meaning: 'огонь (упрощ.)', role: 'semantic' },
    ],
    etymology: '«Огонь» + «Яо» = «сжигать».',
    mnemonic: 'Огонь Яо = «жечь».',
  },
  爪: {
    character: '爪',
    strokeCount: 4,
    radical: { character: '爪', number: 88, name: '爪', meaning: 'коготь' },
    structure: 'simple',
    components: [
      { character: '爪', pinyin: 'zhǎo', meaning: 'коготь/лапа', role: 'both' },
    ],
    etymology: 'Изображение лапы с когтями.',
    mnemonic: 'Когти = «коготь».',
  },
  爬: {
    character: '爬',
    strokeCount: 8,
    radical: { character: '爪', number: 88, name: '爪', meaning: 'коготь' },
    structure: 'left-right',
    components: [
      { character: '爪', pinyin: null, meaning: 'коготь', role: 'semantic' },
      { character: '巴', pinyin: 'bā', meaning: 'жаться (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Когти» + «жаться» = «ползти, карабкаться».',
    mnemonic: '«Когтями» карабкаться = «ползти».',
  },
  父: {
    character: '父',
    strokeCount: 4,
    radical: { character: '父', number: 88, name: '父', meaning: 'отец' },
    structure: 'simple',
    components: [
      { character: '父', pinyin: 'fù', meaning: 'отец', role: 'both' },
    ],
    etymology: 'Изображение отца с посохом/топором.',
    mnemonic: 'Мужчина с посохом = «отец».',
  },
  爷: {
    character: '爷',
    strokeCount: 6,
    radical: { character: '父', number: 88, name: '父', meaning: 'отец' },
    structure: 'top-bottom',
    components: [
      { character: '父', pinyin: 'fù', meaning: 'отец', role: 'semantic' },
      { character: '卩', pinyin: null, meaning: 'печать (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Отец отца» = «дедушка».',
    mnemonic: 'Отец-«печать» = «дедушка».',
  },
  爸: {
    character: '爸',
    strokeCount: 8,
    radical: { character: '父', number: 88, name: '父', meaning: 'отец' },
    structure: 'left-right',
    components: [
      { character: '父', pinyin: null, meaning: 'отец', role: 'semantic' },
      { character: '巴', pinyin: 'bā', meaning: 'жаться (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Отец» в ласкательной форме = «папа».',
    mnemonic: 'Отец-«Ба» = «папа».',
  },
  牛: {
    character: '牛',
    strokeCount: 4,
    radical: { character: '牛', number: 93, name: '牛', meaning: 'корова' },
    structure: 'simple',
    components: [
      { character: '牛', pinyin: 'niú', meaning: 'корова/бык', role: 'both' },
    ],
    etymology: 'Изображение быка с рогами.',
    mnemonic: 'Рога = «корова».',
  },
  物: {
    character: '物',
    strokeCount: 8,
    radical: { character: '牛', number: 93, name: '牛', meaning: 'корова' },
    structure: 'left-right',
    components: [
      { character: '牛', pinyin: null, meaning: 'бык', role: 'semantic' },
      { character: '勿', pinyin: 'wù', meaning: 'не (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Скот» = «вещь, существо».',
    mnemonic: 'Скот + «нет» = «вещь».',
  },
  特: {
    character: '特',
    strokeCount: 10,
    radical: { character: '牛', number: 93, name: '牛', meaning: 'корова' },
    structure: 'left-right',
    components: [
      { character: '牛', pinyin: null, meaning: 'бык', role: 'semantic' },
      { character: '寺', pinyin: 'sì', meaning: 'храм (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Особый» бык для жертвоприношения = «особый».',
    mnemonic: '«Храм»-«бык» = «особый».',
  },
  狗: {
    character: '狗',
    strokeCount: 8,
    radical: { character: '犭', number: 94, name: '犬', meaning: 'собака' },
    structure: 'left-right',
    components: [
      { character: '犭', pinyin: null, meaning: 'собака (упрощ.)', role: 'semantic' },
      { character: '句', pinyin: 'jù', meaning: 'фраза (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Собака» + «фраза» = «собака».',
    mnemonic: '«Собака» + «фраза» = «собака».',
  },
  猫: {
    character: '猫',
    strokeCount: 11,
    radical: { character: '犭', number: 94, name: '犬', meaning: 'собака' },
    structure: 'left-right',
    components: [
      { character: '犭', pinyin: null, meaning: 'собака (зоо-)', role: 'semantic' },
      { character: '苗', pinyin: 'miáo', meaning: 'росток (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Зоо-радикал + «росток» = «кошка».',
    mnemonic: '«Зверь»-«росток» = «кошка».',
  },
  王: {
    character: '王',
    strokeCount: 4,
    radical: { character: '王', number: 96, name: '王', meaning: 'король' },
    structure: 'simple',
    components: [
      { character: '王', pinyin: 'wáng', meaning: 'правитель/нефрит', role: 'both' },
    ],
    etymology: 'Крест-накрест — символ нефритового топора правителя.',
    mnemonic: 'Крест-накрест = «король».',
  },
  玩: {
    character: '玩',
    strokeCount: 7,
    radical: { character: '王', number: 96, name: '王', meaning: 'нефрит' },
    structure: 'left-right',
    components: [
      { character: '王', pinyin: null, meaning: 'нефрит/яшма', role: 'semantic' },
      { character: '元', pinyin: 'yuán', meaning: 'первоначальный (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Играть с яшмой» = «играть, забавляться».',
    mnemonic: '«Яшма» + «первоначальный» = «играть».',
  },
  瓜: {
    character: '瓜',
    strokeCount: 5,
    radical: { character: '瓜', number: 97, name: '瓜', meaning: 'тыква' },
    structure: 'simple',
    components: [
      { character: '瓜', pinyin: 'guā', meaning: 'тыква/дыня', role: 'both' },
    ],
    etymology: 'Изображение плода с усиками.',
    mnemonic: 'Плод с хвостиком = «тыква».',
  },
  用: {
    character: '用',
    strokeCount: 5,
    radical: { character: '用', number: 101, name: '用', meaning: 'использовать' },
    structure: 'simple',
    components: [
      { character: '用', pinyin: 'yòng', meaning: 'использовать', role: 'both' },
    ],
    etymology: 'Изначально изображение колокола-«юн» (особая форма).',
    mnemonic: 'Колокол-«юн» = «использовать».',
  },
  田: {
    character: '田',
    strokeCount: 5,
    radical: { character: '田', number: 102, name: '田', meaning: 'поле' },
    structure: 'simple',
    components: [
      { character: '田', pinyin: 'tián', meaning: 'поле (делянка)', role: 'both' },
    ],
    etymology: 'Поле, разделённое на 4 части межами.',
    mnemonic: 'Квадрат с крестом = «поле».',
  },
  由: {
    character: '由',
    strokeCount: 5,
    radical: { character: '田', number: 102, name: '田', meaning: 'поле' },
    structure: 'top-bottom',
    components: [
      { character: '田', pinyin: null, meaning: 'поле', role: 'semantic' },
      { character: '幺', pinyin: 'yāo', meaning: 'нить (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Нить на поле» = «причина, от».',
    mnemonic: 'Нить идёт от поля = «от, из-за».',
  },
  电: {
    character: '电',
    strokeCount: 5,
    radical: { character: '电', number: 102, name: '雨', meaning: 'дождь/молния' },
    structure: 'simple',
    components: [
      { character: '电', pinyin: 'diàn', meaning: 'молния/электричество', role: 'both' },
    ],
    etymology: 'Изначально знак молнии; позже — «электричество».',
    mnemonic: 'Зигзаг молнии = «электричество».',
  },
  男: {
    character: '男',
    strokeCount: 7,
    radical: { character: '田', number: 102, name: '田', meaning: 'поле' },
    structure: 'top-bottom',
    components: [
      { character: '田', pinyin: null, meaning: 'поле', role: 'semantic' },
      { character: '力', pinyin: null, meaning: 'сила', role: 'semantic' },
    ],
    etymology: '«Сила на поле» = «мужчина, работник».',
    mnemonic: '«Сила» + «поле» = «мужчина».',
  },
  界: {
    character: '界',
    strokeCount: 9,
    radical: { character: '田', number: 102, name: '田', meaning: 'поле' },
    structure: 'left-right',
    components: [
      { character: '田', pinyin: null, meaning: 'поле', role: 'semantic' },
      { character: '介', pinyin: 'jiè', meaning: 'между (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Между полями» = «граница, мир».',
    mnemonic: '«Поле» + «между» = «граница».',
  },
  病: {
    character: '病',
    strokeCount: 10,
    radical: { character: '疒', number: 104, name: '疒', meaning: 'болезнь' },
    structure: 'left-right',
    components: [
      { character: '疒', pinyin: null, meaning: 'болезнь', role: 'semantic' },
      { character: '丙', pinyin: 'bǐng', meaning: 'третий (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Болезнь» + «третий» = «заболевание».',
    mnemonic: '«Болезнь» + «третий» = «болезнь».',
  },
  白: {
    character: '白',
    strokeCount: 5,
    radical: { character: '白', number: 106, name: '白', meaning: 'белый' },
    structure: 'simple',
    components: [
      { character: '白', pinyin: 'bái', meaning: 'белый/ясный', role: 'both' },
    ],
    etymology: 'Большой палец или «сверкающий» — символ ясности.',
    mnemonic: 'Белое пятно = «белый».',
  },
  百: {
    character: '百',
    strokeCount: 6,
    radical: { character: '白', number: 106, name: '白', meaning: 'белый' },
    structure: 'top-bottom',
    components: [
      { character: '一', pinyin: null, meaning: 'один', role: 'semantic' },
      { character: '白', pinyin: null, meaning: 'много (искаж.)', role: 'semantic' },
    ],
    etymology: '«Много белого» = «сто».',
    mnemonic: '«Один» + «белый» = «сто».',
  },
  的: {
    character: '的',
    strokeCount: 8,
    radical: { character: '白', number: 106, name: '白', meaning: 'белый' },
    structure: 'left-right',
    components: [
      { character: '白', pinyin: null, meaning: 'белый (искаж.)', role: 'semantic' },
      { character: '勺', pinyin: 'sháo', meaning: 'ложка (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Белый» + «ложка» = «цель, суффикс прилагательного».',
    mnemonic: 'Чёткий «белый»-«ложка» = «…-ов/-ый».',
  },
  眼: {
    character: '眼',
    strokeCount: 11,
    radical: { character: '目', number: 109, name: '目', meaning: 'глаз' },
    structure: 'left-right',
    components: [
      { character: '目', pinyin: null, meaning: 'глаз', role: 'semantic' },
      { character: '艮', pinyin: 'gèn', meaning: 'упорный (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Глаз» + «упорный» = «глаз».',
    mnemonic: '«Глаз» + «упорный» = «глаз».',
  },
  睛: {
    character: '睛',
    strokeCount: 13,
    radical: { character: '目', number: 109, name: '目', meaning: 'глаз' },
    structure: 'left-right',
    components: [
      { character: '目', pinyin: null, meaning: 'глаз', role: 'semantic' },
      { character: '青', pinyin: 'qīng', meaning: 'синева (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Глаз» + «синева» = «зрачок».',
    mnemonic: '«Глаз» + «синева» = «зрачок».',
  },
  耳: {
    character: '耳',
    strokeCount: 6,
    radical: { character: '耳', number: 111, name: '耳', meaning: 'ухо' },
    structure: 'simple',
    components: [
      { character: '耳', pinyin: 'ěr', meaning: 'ухо', role: 'both' },
    ],
    etymology: 'Изображение уха (с завитком).',
    mnemonic: 'Завиток = «ухо».',
  },
  听: {
    character: '听',
    strokeCount: 7,
    radical: { character: '口', number: 30, name: '口', meaning: 'рот' },
    structure: 'left-right',
    components: [
      { character: '口', pinyin: null, meaning: 'рот', role: 'semantic' },
      { character: '斤', pinyin: 'jīn', meaning: 'топор (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Рот» + «топор» = «слушать».',
    mnemonic: '«Ртом» воспринимать = «слушать».',
  },
  肉: {
    character: '肉',
    strokeCount: 6,
    radical: { character: '肉', number: 130, name: '肉', meaning: 'мясо' },
    structure: 'simple',
    components: [
      { character: '肉', pinyin: 'ròu', meaning: 'мясо', role: 'both' },
    ],
    etymology: 'Схематичный кусок мяса (с рёбрами).',
    mnemonic: 'Полосатый кусок = «мясо».',
  },
  衣: {
    character: '衣',
    strokeCount: 6,
    radical: { character: '衣', number: 145, name: '衣', meaning: 'одежда' },
    structure: 'simple',
    components: [
      { character: '衣', pinyin: 'yī', meaning: 'одежда', role: 'both' },
    ],
    etymology: 'Изображение одежды с воротом и подолом.',
    mnemonic: 'Ворот + подол = «одежда».',
  },
  言: {
    character: '言',
    strokeCount: 7,
    radical: { character: '言', number: 149, name: '言', meaning: 'речь' },
    structure: 'simple',
    components: [
      { character: '言', pinyin: 'yán', meaning: 'речь', role: 'both' },
    ],
    etymology: 'Рот с выходящим звуком и языком.',
    mnemonic: 'Рот + звук = «речь».',
  },
  谁: {
    character: '谁',
    strokeCount: 9,
    radical: { character: '讠', number: 149, name: '言', meaning: 'речь' },
    structure: 'left-right',
    components: [
      { character: '讠', pinyin: null, meaning: 'речь (упрощ.)', role: 'semantic' },
      { character: '隹', pinyin: 'zhuī', meaning: 'птица (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Речь» + «птица» = «кто?».',
    mnemonic: '«Речь» + «птица» = «кто?».',
  },
  走: {
    character: '走',
    strokeCount: 7,
    radical: { character: '走', number: 156, name: '走', meaning: 'бежать' },
    structure: 'simple',
    components: [
      { character: '走', pinyin: 'zǒu', meaning: 'бежать/идти', role: 'both' },
    ],
    etymology: 'Изображение бегущего человека с развевающимися руками.',
    mnemonic: 'Бегущий = «идти».',
  },
  起: {
    character: '起',
    strokeCount: 10,
    radical: { character: '走', number: 156, name: '走', meaning: 'бежать' },
    structure: 'top-bottom',
    components: [
      { character: '走', pinyin: null, meaning: 'идти', role: 'semantic' },
      { character: '己', pinyin: null, meaning: 'сам (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Идти самому» = «встать, подняться».',
    mnemonic: '«Сам» идёт = «встать».',
  },
  跑: {
    character: '跑',
    strokeCount: 12,
    radical: { character: '足', number: 157, name: '足', meaning: 'нога' },
    structure: 'left-right',
    components: [
      { character: '足', pinyin: null, meaning: 'нога', role: 'semantic' },
      { character: '包', pinyin: 'bāo', meaning: 'обёртка (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Нога» + «обёртка» = «бежать».',
    mnemonic: 'Быстрая «нога» = «бежать».',
  },
  跳: {
    character: '跳',
    strokeCount: 13,
    radical: { character: '足', number: 157, name: '足', meaning: 'нога' },
    structure: 'left-right',
    components: [
      { character: '足', pinyin: null, meaning: 'нога', role: 'semantic' },
      { character: '兆', pinyin: 'zhào', meaning: 'знак (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Нога» + «знак» = «прыгать».',
    mnemonic: '«Ногой» — «знак» = «прыгать».',
  },
  车: {
    character: '车',
    strokeCount: 4,
    radical: { character: '车', number: 159, name: '车', meaning: 'повозка' },
    structure: 'simple',
    components: [
      { character: '车', pinyin: 'chē', meaning: 'повозка', role: 'both' },
    ],
    etymology: 'Схематичный вид сверху на повозку с осью.',
    mnemonic: 'Ось + колёса = «повозка».',
  },
  边: {
    character: '边',
    strokeCount: 7,
    radical: { character: '辶', number: 162, name: '辶', meaning: 'идти' },
    structure: 'left-right',
    components: [
      { character: '力', pinyin: null, meaning: 'сила', role: 'semantic' },
      { character: '辶', pinyin: null, meaning: 'движение', role: 'semantic' },
    ],
    etymology: '«Сила» + «движение» = «край, граница».',
    mnemonic: '«Сила» в движении = «край».',
  },
  还: {
    character: '还',
    strokeCount: 7,
    radical: { character: '辶', number: 162, name: '辶', meaning: 'идти' },
    structure: 'left-right',
    components: [
      { character: '不', pinyin: null, meaning: 'нет', role: 'semantic' },
      { character: '辶', pinyin: null, meaning: 'идти', role: 'semantic' },
    ],
    etymology: '«Нет»-«идти» = «ещё, возвращать».',
    mnemonic: '«Нет» в движении = «ещё».',
  },
  这: {
    character: '这',
    strokeCount: 7,
    radical: { character: '辶', number: 162, name: '辶', meaning: 'идти' },
    structure: 'left-right',
    components: [
      { character: '文', pinyin: null, meaning: 'культура', role: 'semantic' },
      { character: '辶', pinyin: null, meaning: 'идти', role: 'semantic' },
    ],
    etymology: '«Культура» + «идти» = «этот».',
    mnemonic: '«Культура»-«идти» = «этот».',
  },
  进: {
    character: '进',
    strokeCount: 6,
    radical: { character: '辶', number: 162, name: '辶', meaning: 'идти' },
    structure: 'left-right',
    components: [
      { character: '井', pinyin: null, meaning: 'колодец', role: 'semantic' },
      { character: '辶', pinyin: null, meaning: 'идти', role: 'semantic' },
    ],
    etymology: '«Колодец» + «идти» = «входить».',
    mnemonic: 'Войти в «колодец» = «входить».',
  },
  远: {
    character: '远',
    strokeCount: 7,
    radical: { character: '辶', number: 162, name: '辶', meaning: 'идти' },
    structure: 'left-right',
    components: [
      { character: '元', pinyin: 'yuán', meaning: 'первоначальный (фонетик)', role: 'phonetic' },
      { character: '辶', pinyin: null, meaning: 'идти', role: 'semantic' },
    ],
    etymology: '«Первоначальный» путь = «далёкий».',
    mnemonic: 'Долгий путь = «далёкий».',
  },
  门: {
    character: '门',
    strokeCount: 3,
    radical: { character: '门', number: 169, name: '门', meaning: 'ворота' },
    structure: 'simple',
    components: [
      { character: '门', pinyin: 'mén', meaning: 'ворота', role: 'both' },
    ],
    etymology: 'Двустворчатые ворота.',
    mnemonic: 'Две створки = «ворота».',
  },
  间: {
    character: '间',
    strokeCount: 12,
    radical: { character: '门', number: 169, name: '门', meaning: 'ворота' },
    structure: 'surrounding',
    components: [
      { character: '门', pinyin: null, meaning: 'ворота', role: 'semantic' },
      { character: '日', pinyin: 'rì', meaning: 'солнце (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Солнце между воротами» = «промежуток, комната».',
    mnemonic: '«Солнце» в «воротах» = «комната».',
  },
  雨: {
    character: '雨',
    strokeCount: 8,
    radical: { character: '雨', number: 173, name: '雨', meaning: 'дождь' },
    structure: 'top-bottom',
    components: [
      { character: '雨', pinyin: 'yǔ', meaning: 'дождь', role: 'both' },
    ],
    etymology: 'Туча с падающими каплями.',
    mnemonic: 'Капли сверху = «дождь».',
  },
  雪: {
    character: '雪',
    strokeCount: 11,
    radical: { character: '雨', number: 173, name: '雨', meaning: 'дождь' },
    structure: 'top-bottom',
    components: [
      { character: '雨', pinyin: null, meaning: 'дождь', role: 'semantic' },
      { character: '彐', pinyin: 'jì', meaning: 'поросёнок (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Дождь» с «поросёнком» (форма снежинки) = «снег».',
    mnemonic: '«Дождь» = «снег» (холодный).',
  },
  音: {
    character: '音',
    strokeCount: 9,
    radical: { character: '音', number: 180, name: '音', meaning: 'звук' },
    structure: 'top-bottom',
    components: [
      { character: '立', pinyin: 'lì', meaning: 'стоять (искаж.)', role: 'semantic' },
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
    ],
    etymology: '«Стоящий» звук = «звук».',
    mnemonic: '«Стоящий» звук = «звук».',
  },
  页: {
    character: '页',
    strokeCount: 4,
    radical: { character: '页', number: 181, name: '页', meaning: 'страница' },
    structure: 'simple',
    components: [
      { character: '页', pinyin: 'yè', meaning: 'голова/лист', role: 'both' },
    ],
    etymology: 'Голова или страница (исторически — изображение головы с волосами).',
    mnemonic: '«Лист»-«голова» = «страница».',
  },
  风: {
    character: '风',
    strokeCount: 4,
    radical: { character: '风', number: 182, name: '风', meaning: 'ветер' },
    structure: 'simple',
    components: [
      { character: '风', pinyin: 'fēng', meaning: 'ветер', role: 'both' },
    ],
    etymology: 'Схематичный флюгер или поток воздуха.',
    mnemonic: '«Поток» = «ветер».',
  },
  飞: {
    character: '飞',
    strokeCount: 3,
    radical: { character: '飞', number: 183, name: '飞', meaning: 'летать' },
    structure: 'simple',
    components: [
      { character: '飞', pinyin: 'fēi', meaning: 'летать', role: 'both' },
    ],
    etymology: 'Расправленные крылья птицы.',
    mnemonic: '«Крылья» = «летать».',
  },
  鱼: {
    character: '鱼',
    strokeCount: 8,
    radical: { character: '鱼', number: 195, name: '鱼', meaning: 'рыба' },
    structure: 'simple',
    components: [
      { character: '鱼', pinyin: 'yú', meaning: 'рыба', role: 'both' },
    ],
    etymology: 'Изображение рыбы с головой, телом и хвостом.',
    mnemonic: 'Голова + хвост = «рыба».',
  },
  鸡: {
    character: '鸡',
    strokeCount: 7,
    radical: { character: '鸟', number: 196, name: '鸟', meaning: 'птица' },
    structure: 'left-right',
    components: [
      { character: '鸟', pinyin: null, meaning: 'птица', role: 'semantic' },
      { character: '奓', pinyin: null, meaning: 'большой (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Большая птица» = «курица».',
    mnemonic: 'Большая «птица» = «курица».',
  },
  蛋: {
    character: '蛋',
    strokeCount: 13,
    radical: { character: '蛋', number: 197, name: '蛋', meaning: 'яйцо' },
    structure: 'top-bottom',
    components: [
      { character: '旦', pinyin: 'dàn', meaning: 'заря (фонетик)', role: 'phonetic' },
      { character: '虫', pinyin: null, meaning: 'насекомое', role: 'semantic' },
    ],
    etymology: '«Заря» от «насекомого» = «яйцо».',
    mnemonic: '«Заря» + «насекомое» = «яйцо».',
  },
  黄: {
    character: '黄',
    strokeCount: 11,
    radical: { character: '黄', number: 201, name: '黄', meaning: 'жёлтый' },
    structure: 'overlap',
    components: [
      { character: '黄', pinyin: 'huáng', meaning: 'жёлтый/янтарь', role: 'both' },
    ],
    etymology: 'Исторически — знак «жертвенной яшмы» (жёлтый камень).',
    mnemonic: '«Жертвенный камень» = «жёлтый».',
  },
  // ===== HSK 1 (дополнение) =====
  中: {
    character: '中',
    strokeCount: 4,
    radical: { character: '丨', number: 2, name: '丨', meaning: 'вертикаль' },
    structure: 'overlap',
    components: [
      { character: '口', pinyin: null, meaning: 'рот/поле', role: 'semantic' },
      { character: '丨', pinyin: null, meaning: 'вертикаль/стрела', role: 'semantic' },
    ],
    etymology: 'Вертикаль (стрела, шест) проходит через центр поля = «середина, центр».',
    mnemonic: 'Стрела через центр = «середина».',
  },
  好: {
    character: '好',
    strokeCount: 6,
    radical: { character: '女', number: 38, name: '女', meaning: 'женщина' },
    structure: 'left-right',
    components: [
      { character: '女', pinyin: 'nǚ', meaning: 'женщина', role: 'semantic' },
      { character: '子', pinyin: 'zǐ', meaning: 'ребёнок (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Женщина с ребёнком = «хорошо, прекрасно».',
    mnemonic: '«Женщина» + «ребёнок» = «хорошо».',
  },
  人: {
    character: '人',
    strokeCount: 2,
    radical: { character: '人', number: 9, name: '人', meaning: 'человек' },
    structure: 'simple',
    components: [
      { character: '人', pinyin: 'rén', meaning: 'человек', role: 'both' },
    ],
    etymology: 'Изображение согнувшегося человека.',
    mnemonic: 'Согнутая фигура = «человек».',
  },
  我: {
    character: '我',
    strokeCount: 7,
    radical: { character: '戈', number: 62, name: '戈', meaning: 'копьё' },
    structure: 'left-right',
    components: [
      { character: '手', pinyin: null, meaning: 'рука (искаж.)', role: 'semantic' },
      { character: '戈', pinyin: 'gē', meaning: 'копьё', role: 'semantic' },
    ],
    etymology: '«Рука с копьём» = «я, моё» (защита своего).',
    mnemonic: '«Рука» с «копьём» = «я, моё».',
  },
  你: {
    character: '你',
    strokeCount: 7,
    radical: { character: '亻', number: 9, name: '人', meaning: 'человек' },
    structure: 'left-right',
    components: [
      { character: '亻', pinyin: null, meaning: 'человек (упрощ.)', role: 'semantic' },
      { character: '尔', pinyin: 'ěr', meaning: 'ты (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Ты» в человеке = «ты».',
    mnemonic: '«Человек»-«ты» = «ты».',
  },
  他: {
    character: '他',
    strokeCount: 5,
    radical: { character: '亻', number: 9, name: '人', meaning: 'человек' },
    structure: 'left-right',
    components: [
      { character: '亻', pinyin: null, meaning: 'человек (упрощ.)', role: 'semantic' },
      { character: '也', pinyin: 'yě', meaning: 'тоже (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Тоже человек» = «он».',
    mnemonic: '«Человек»-«тоже» = «он».',
  },
  是: {
    character: '是',
    strokeCount: 9,
    radical: { character: '日', number: 72, name: '日', meaning: 'солнце' },
    structure: 'top-bottom',
    components: [
      { character: '日', pinyin: null, meaning: 'солнце', role: 'semantic' },
      { character: '疋', pinyin: 'shū', meaning: 'верно/правильно', role: 'semantic' },
    ],
    etymology: '«Солнце» + «верно» = «являться, правильно».',
    mnemonic: '«Солнце» = «правда» = «являться».',
  },
  在: {
    character: '在',
    strokeCount: 6,
    radical: { character: '土', number: 32, name: '土', meaning: 'земля' },
    structure: 'surrounding',
    components: [
      { character: '土', pinyin: null, meaning: 'земля', role: 'semantic' },
      { character: '才', pinyin: 'cái', meaning: 'способный (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Способный» на «земле» = «находиться».',
    mnemonic: 'Стоять на «земле» = «находиться».',
  },
  有: {
    character: '有',
    strokeCount: 6,
    radical: { character: '丶', number: 4, name: '丶', meaning: 'точка' },
    structure: 'top-bottom',
    components: [
      { character: '𠂇', pinyin: null, meaning: 'крышка/правая рука', role: 'semantic' },
      { character: '月', pinyin: null, meaning: 'луна (искаж. «肉»)', role: 'semantic' },
    ],
    etymology: '«Рука держит мясо» = «иметь».',
    mnemonic: '«Рука» с «мясом» = «иметь».',
  },
  来: {
    character: '来',
    strokeCount: 7,
    radical: { character: '木', number: 75, name: '木', meaning: 'дерево' },
    structure: 'overlap',
    components: [
      { character: '木', pinyin: null, meaning: 'дерево', role: 'semantic' },
      { character: '未', pinyin: 'wèi', meaning: 'ещё нет (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Дерево» + «ещё нет» = «прийти» (ещё не было).',
    mnemonic: '«Дерево» идёт = «прийти».',
  },
  去: {
    character: '去',
    strokeCount: 5,
    radical: { character: '土', number: 32, name: '土', meaning: 'земля' },
    structure: 'overlap',
    components: [
      { character: '土', pinyin: null, meaning: 'земля', role: 'semantic' },
      { character: '厶', pinyin: null, meaning: 'частное', role: 'semantic' },
    ],
    etymology: 'Уйти от «земли» = «уходить».',
    mnemonic: 'Шаг от «земли» = «уйти».',
  },
  看: {
    character: '看',
    strokeCount: 9,
    radical: { character: '目', number: 109, name: '目', meaning: 'глаз' },
    structure: 'top-bottom',
    components: [
      { character: '目', pinyin: null, meaning: 'глаз', role: 'semantic' },
      { character: '手', pinyin: 'kàn', meaning: 'рука (искаж.)', role: 'phonetic' },
    ],
    etymology: '«Рука» у «глаза» = «смотреть, присматривать».',
    mnemonic: '«Рука» у «глаза» = «смотреть».',
  },
  说: {
    character: '说',
    strokeCount: 9,
    radical: { character: '讠', number: 149, name: '言', meaning: 'речь' },
    structure: 'left-right',
    components: [
      { character: '讠', pinyin: null, meaning: 'речь (упрощ.)', role: 'semantic' },
      { character: '兑', pinyin: 'duì', meaning: 'обмен (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Речь» + «обмен» = «говорить».',
    mnemonic: '«Речь» + «обмен» = «говорить».',
  },
  学: {
    character: '学',
    strokeCount: 8,
    radical: { character: '子', number: 39, name: '子', meaning: 'ребёнок' },
    structure: 'top-bottom',
    components: [
      { character: '⺍', pinyin: null, meaning: 'руки (упрощ. 爪)', role: 'semantic' },
      { character: '子', pinyin: null, meaning: 'ребёнок', role: 'semantic' },
    ],
    etymology: 'Ребёнок, работающий руками под крышей = «учиться».',
    mnemonic: '«Ребёнок» под «руками» = «учиться».',
  },
  会: {
    character: '会',
    strokeCount: 6,
    radical: { character: '人', number: 9, name: '人', meaning: 'человек' },
    structure: 'overlap',
    components: [
      { character: '人', pinyin: null, meaning: 'человек', role: 'semantic' },
      { character: '云', pinyin: 'yún', meaning: 'облако (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Люди» под «облаком» = «встреча, уметь».',
    mnemonic: '«Люди» в «облаке» = «уметь, встреча».',
  },
  能: {
    character: '能',
    strokeCount: 10,
    radical: { character: '月', number: 74, name: '月', meaning: 'плоть' },
    structure: 'left-right',
    components: [
      { character: '月', pinyin: null, meaning: 'плоть (искаж. 月)', role: 'semantic' },
      { character: '能', pinyin: 'néng', meaning: 'медведь (искаж.)', role: 'semantic' },
    ],
    etymology: '«Плоть» силы = «мочь, способность».',
    mnemonic: '«Плоть» + «сила» = «мочь».',
  },
  大: {
    character: '大',
    strokeCount: 3,
    radical: { character: '大', number: 37, name: '大', meaning: 'большой' },
    structure: 'simple',
    components: [
      { character: '大', pinyin: 'dà', meaning: 'большой', role: 'both' },
    ],
    etymology: 'Изображение человека с раскинутыми руками — «большой».',
    mnemonic: 'Раскинутые руки = «большой».',
  },
  小: {
    character: '小',
    strokeCount: 3,
    radical: { character: '小', number: 45, name: '小', meaning: 'маленький' },
    structure: 'simple',
    components: [
      { character: '小', pinyin: 'xiǎo', meaning: 'маленький', role: 'both' },
    ],
    etymology: 'Три точки/штриха, уменьшающиеся в центре — «маленький».',
    mnemonic: 'Уменьшающиеся штрихи = «маленький».',
  },
  多: {
    character: '多',
    strokeCount: 6,
    radical: { character: '夕', number: 36, name: '夕', meaning: 'вечер' },
    structure: 'top-bottom',
    components: [
      { character: '夕', pinyin: null, meaning: 'вечер', role: 'semantic' },
      { character: '夕', pinyin: null, meaning: 'вечер', role: 'semantic' },
    ],
    etymology: 'Двойной «вечер» = «много» (несколько вечеров).',
    mnemonic: 'Два «вечера» = «много».',
  },
  少: {
    character: '少',
    strokeCount: 4,
    radical: { character: '小', number: 45, name: '小', meaning: 'маленький' },
    structure: 'top-bottom',
    components: [
      { character: '小', pinyin: null, meaning: 'маленький', role: 'semantic' },
      { character: '⺁', pinyin: null, meaning: 'птица (искаж.)', role: 'semantic' },
    ],
    etymology: 'Маленькая «птица» (ещё не взлетела) = «мало, молодой».',
    mnemonic: 'Маленькая «птица» = «мало».',
  },
  天: {
    character: '天',
    strokeCount: 4,
    radical: { character: '大', number: 37, name: '大', meaning: 'большой' },
    structure: 'top-bottom',
    components: [
      { character: '一', pinyin: null, meaning: 'небо/крыша', role: 'semantic' },
      { character: '大', pinyin: null, meaning: 'большой', role: 'semantic' },
    ],
    etymology: '«Большой» под «крышей неба» = «небо».',
    mnemonic: '«Большой» под крышей = «небо».',
  },
  年: {
    character: '年',
    strokeCount: 6,
    radical: { character: '干', number: 51, name: '干', meaning: 'сухой' },
    structure: 'top-bottom',
    components: [
      { character: '禾', pinyin: null, meaning: 'зерно/колос', role: 'semantic' },
      { character: '干', pinyin: null, meaning: 'основа/ствол', role: 'semantic' },
    ],
    etymology: 'Созревание зерна на стебле = «год, жатва».',
    mnemonic: 'Колос на стебле = «год».',
  },
  点: {
    character: '点',
    strokeCount: 9,
    radical: { character: '丶', number: 4, name: '丶', meaning: 'точка' },
    structure: 'left-right',
    components: [
      { character: '丶', pinyin: null, meaning: 'точка/огонь', role: 'semantic' },
      { character: '占', pinyin: 'zhàn', meaning: 'гадать (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Точка» + «гадать» = «точка, время, капля».',
    mnemonic: '«Точка» + «гадать» = «точка, час».',
  },
  见: {
    character: '见',
    strokeCount: 4,
    radical: { character: '见', number: 147, name: '见', meaning: 'видеть' },
    structure: 'simple',
    components: [
      { character: '见', pinyin: 'jiàn', meaning: 'видеть (глаз)', role: 'both' },
    ],
    etymology: 'Силуэт человека с большим глазом — «видеть».',
    mnemonic: 'Глаз + тело = «видеть».',
  },
  读: {
    character: '读',
    strokeCount: 10,
    radical: { character: '讠', number: 149, name: '言', meaning: 'речь' },
    structure: 'left-right',
    components: [
      { character: '讠', pinyin: null, meaning: 'речь (упрощ.)', role: 'semantic' },
      { character: '卖', pinyin: 'mài', meaning: 'продавать (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Речь» + «продавать» = «читать вслух».',
    mnemonic: '«Речь»-«продавать» = «читать».',
  },
  写: {
    character: '写',
    strokeCount: 5,
    radical: { character: '冖', number: 14, name: '冖', meaning: 'покрывало' },
    structure: 'top-bottom',
    components: [
      { character: '冖', pinyin: null, meaning: 'покрывало', role: 'semantic' },
      { character: '与', pinyin: 'yǔ', meaning: 'давать (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Давать» под «покрывалом» = «писать».',
    mnemonic: 'Под «покрывалом» «давать» = «писать».',
  },
  朋: {
    character: '朋',
    strokeCount: 8,
    radical: { character: '月', number: 74, name: '月', meaning: 'луна/плоть' },
    structure: 'left-right',
    components: [
      { character: '月', pinyin: null, meaning: 'плоть (искаж.)', role: 'semantic' },
      { character: '月', pinyin: null, meaning: 'плоть (искаж.)', role: 'semantic' },
    ],
    etymology: 'Две «половинки» одной плоти = «друзья».',
    mnemonic: 'Две «половинки» = «друзья».',
  },
  友: {
    character: '友',
    strokeCount: 4,
    radical: { character: '又', number: 29, name: '又', meaning: 'снова' },
    structure: 'left-right',
    components: [
      { character: '又', pinyin: null, meaning: 'правая рука', role: 'semantic' },
    ],
    etymology: 'Протянутая «рука» = «друг».',
    mnemonic: '«Рука» = «друг».',
  },
  妈: {
    character: '妈',
    strokeCount: 6,
    radical: { character: '女', number: 38, name: '女', meaning: 'женщина' },
    structure: 'left-right',
    components: [
      { character: '女', pinyin: null, meaning: 'женщина', role: 'semantic' },
      { character: '马', pinyin: 'mǎ', meaning: 'лошадь (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Женщина + «лошадь» (фонетик) = «мама».',
    mnemonic: '«Женщина»-«лошадь» = «мама».',
  },
  家: {
    character: '家',
    strokeCount: 10,
    radical: { character: '宀', number: 40, name: '宀', meaning: 'крыша' },
    structure: 'top-bottom',
    components: [
      { character: '宀', pinyin: null, meaning: 'крыша', role: 'semantic' },
      { character: '豕', pinyin: 'shǐ', meaning: 'свинья (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Свинья» под крышей = «дом, семья».',
    mnemonic: '«Свинья» под «крышей» = «дом».',
  },
  书: {
    character: '书',
    strokeCount: 4,
    radical: { character: '乛', number: 5, name: '乙', meaning: 'второй' },
    structure: 'simple',
    components: [
      { character: '聿', pinyin: null, meaning: 'кисть', role: 'semantic' },
    ],
    etymology: '«Кисть для письма» = «книга».',
    mnemonic: '«Кисть» = «книга».',
  },
  笔: {
    character: '笔',
    strokeCount: 10,
    radical: { character: '竹', number: 118, name: '竹', meaning: 'бамбук' },
    structure: 'top-bottom',
    components: [
      { character: '⺮', pinyin: null, meaning: 'бамбук (упрощ.)', role: 'semantic' },
      { character: '毛', pinyin: 'máo', meaning: 'шерсть', role: 'semantic' },
    ],
    etymology: 'Бамбук с шерстью = «кисть, ручка».',
    mnemonic: '«Бамбук» + «шерсть» = «ручка».',
  },
  食: {
    character: '食',
    strokeCount: 9,
    radical: { character: '食', number: 184, name: '食', meaning: 'еда' },
    structure: 'top-bottom',
    components: [
      { character: '良', pinyin: 'liáng', meaning: 'хороший (фонетик)', role: 'phonetic' },
      { character: '皿', pinyin: null, meaning: 'сосуд', role: 'semantic' },
    ],
    etymology: '«Хорошее» в «сосуде» = «еда».',
    mnemonic: '«Сосуд» с «хорошим» = «еда».',
  },
  米: {
    character: '米',
    strokeCount: 6,
    radical: { character: '米', number: 119, name: '米', meaning: 'рис' },
    structure: 'simple',
    components: [
      { character: '米', pinyin: 'mǐ', meaning: 'рисовое зерно', role: 'both' },
    ],
    etymology: 'Изображение рисового зерна с шелухой.',
    mnemonic: 'Зерно = «рис».',
  },
  茶: {
    character: '茶',
    strokeCount: 9,
    radical: { character: '艹', number: 140, name: '艹', meaning: 'трава' },
    structure: 'top-bottom',
    components: [
      { character: '艹', pinyin: null, meaning: 'трава', role: 'semantic' },
      { character: '木', pinyin: 'chá', meaning: 'дерево (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Травянистое дерево» = «чай».',
    mnemonic: '«Трава» + «дерево» = «чай».',
  },
  酒: {
    character: '酒',
    strokeCount: 10,
    radical: { character: '酉', number: 164, name: '酉', meaning: 'алкоголь' },
    structure: 'left-right',
    components: [
      { character: '酉', pinyin: null, meaning: 'алкоголь/кувшин', role: 'semantic' },
      { character: '酉', pinyin: 'jiǔ', meaning: 'запад/вечер (фонетик)', role: 'phonetic' },
    ],
    etymology: 'Напиток в «кувшине» = «алкоголь».',
    mnemonic: '«Кувшин» с «вечером» = «вино».',
  },
  菜: {
    character: '菜',
    strokeCount: 11,
    radical: { character: '艹', number: 140, name: '艹', meaning: 'трава' },
    structure: 'top-bottom',
    components: [
      { character: '艹', pinyin: null, meaning: 'трава', role: 'semantic' },
      { character: '采', pinyin: 'cǎi', meaning: 'собирать (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Собирать» траву = «овощи».',
    mnemonic: '«Трава» + «собирать» = «овощи».',
  },
  饭: {
    character: '饭',
    strokeCount: 7,
    radical: { character: '饣', number: 184, name: '食', meaning: 'еда' },
    structure: 'left-right',
    components: [
      { character: '饣', pinyin: null, meaning: 'еда (упрощ.)', role: 'semantic' },
      { character: '反', pinyin: 'fǎn', meaning: 'обратно (фонетик)', role: 'phonetic' },
    ],
    etymology: '«Еда» + «обратно» = «варёный рис, еда».',
    mnemonic: '«Еда»-«обратно» = «еда».',
  },
  喜: {
    character: '喜',
    strokeCount: 12,
    radical: { character: '口', number: 30, name: '口', meaning: 'рот' },
    structure: 'top-bottom',
    components: [
      { character: '士', pinyin: 'shì', meaning: 'воин', role: 'semantic' },
      { character: '口', pinyin: '口', meaning: 'рот', role: 'semantic' },
      { character: '口', pinyin: null, meaning: 'рот', role: 'semantic' },
    ],
    etymology: '«Рты» на «знамени» (士) — ликование на площади.',
    mnemonic: 'Много ртов + знамя = «радость».',
  },
  爱: {
    character: '爱',
    strokeCount: 10,
    radical: { character: '爫', number: 88, name: '爪', meaning: 'коготь' },
    structure: 'top-bottom',
    components: [
      { character: '爫', pinyin: null, meaning: 'коготь', role: 'semantic' },
      { character: '夂', pinyin: null, meaning: 'медленно', role: 'semantic' },
      { character: '心', pinyin: null, meaning: 'сердце', role: 'semantic' },
    ],
    etymology: '«Когти» в «сердце» = «любить».',
    mnemonic: '«Когти» + «сердце» = «любовь».',
  },
};

export function hasDictionaryEntry(character: string): boolean {
  return Object.prototype.hasOwnProperty.call(ETYMOLOGY_DICTIONARY, character);
}
